import Head from 'next/head'
import { ReactElement } from 'react'
import DashboardLayout from '../../../layout/dashboard'
import DecorationContainer from '../../../container/decoration'

export default function DecorationPage() {
  return (
    <>
      <Head>
        <title>Sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DecorationContainer />
    </>
  )
}

DecorationPage.getLayout = (page: ReactElement) => {
  return <DashboardLayout>{page}</DashboardLayout>
}
