import Head from 'next/head'
import { ReactElement, useMemo, useState } from 'react'
import DashboardLayout from '../../../layout/dashboard'
import DecorationContainer from '../../../container/decoration'
import { Row, Spin } from 'antd'

export default function DecorationPage() {
  const [isLoading, setIsLoading] = useState(true)
  useMemo(() => {
    setTimeout(() => setIsLoading(false), 1000)
  }, [])

  return (
    <>
      <Head>
        <title>Giao diện</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <Row style={{ minHeight: 350, width: '100%' }} align="middle" justify="center">
          <Spin size="large" tip="loading..." />
        </Row>
      ) : (
        <DecorationContainer />
      )}
    </>
  )
}

DecorationPage.getLayout = (page: ReactElement) => {
  return <DashboardLayout>{page}</DashboardLayout>
}
