import Head from 'next/head'
import { ReactElement } from 'react'
import DashboardLayout from '../../../../layout/dashboard'

export default function SaleOrderPage() {
  return (
    <>
      <Head>
        <title>Kênh người bán</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Sale
    </>
  )
}

SaleOrderPage.getLayout = (page: ReactElement) => {
  return <DashboardLayout>{page}</DashboardLayout>
}
