import Head from 'next/head'
import { ReactElement } from 'react'
import DashboardLayout from '../../../../layout/dashboard'
import ProductContainer from '../../../../container/products'

export default function ProductPage() {
  return (
    <>
      <Head>
        <title>Sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductContainer />
    </>
  )
}

ProductPage.getLayout = (page: ReactElement) => {
  return <DashboardLayout>{page}</DashboardLayout>
}
